name: Distribute

on:
  push:
    branches:
    - "master"
    paths:
    - "**.proto"
    - ".github/workflows/**"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Pull source
      uses: actions/checkout@v2

    - name: Prepare build environment
      run: |
        choco install -y protoc --version=3.11.4
      shell: powershell

    - name: Setup folders
      run: |
        New-Item -Path 'dist\cpp' -ItemType Directory
        New-Item -Path 'dist\cs' -ItemType Directory
        New-Item -Path 'dist\js-commonjs' -ItemType Directory
        New-Item -Path 'dist\python' -ItemType Directory
        New-Item -Path 'dist\java' -ItemType Directory
      shell: pwsh

    - name: Download gRPC protoc plugin
      id: download_grpc
      run: |
        $exePath = ./grpc_protoc_inst.ps1
        echo "Downloaded: $exePath"
        echo "::set-output name=plugin_path::$exePath"

    - name: Build protobuf library
      run: |
        $files = Get-Childitem 'vNerve' -Recurse -File -Filter "*.proto" | foreach { $_.FullName}
        $proto_path = (Resolve-Path .).ToString()
        protoc --proto_path=$proto_path --cpp_out=dist/cpp --grpc_out=dist/cpp --plugin=protoc-gen-grpc=${{ steps.download_grpc.outputs.plugin_path }} --csharp_out=dist/cs --java_out=dist/java --python_out=dist/python --js_out=import_style=commonjs,binary:dist/js-commonjs $files
      shell: pwsh

    - name: Distribute
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        user_name: "GitHub Actions"
        user_email: "actions@github.com"
        publish_branch: "dist"
        publish_dir: ./dist
